palette = "catppuccin_mocha"

# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format = """
[ ](bg:sapphire)\
$os\
$username\
[](fg:sapphire bg:overlay1)\
$hostname\
$directory\
[](fg:overlay1 bg:surface0)\
$container\
$env_var\
$git_branch\
$git_status\
$hg_branch\
$pijul_channel\
$vcsh\
[](fg:surface0 bg:crust)\
$crystal\
$deno\
[](fg:crust bg:rosewater)\
$bun\
$fennel\
[](fg:rosewater bg:flamingo)\
[](fg:flamingo bg:pink)\
$raku\
[](fg:pink bg:mauve)\
$dotnet\
$kotlin\
[](fg:mauve bg:red)\
$cmake\
$erlang\
$java\
$openstack\
$red\
$ruby\
$scala\
[](fg:red bg:maroon)\
$package\
[](fg:maroon bg:peach)\
$haxe\
$ocaml\
$rust\
$swift\
[](fg:peach bg:yellow)\
$aws\
$nim\
$guix_shell\
$python\
$zig\
[](fg:yellow bg:green)\
$conda\
$julia\
$memory_usage\
$nodejs\
[](fg:green bg:teal)\
$gradle\
$purescript\
[](fg:teal bg:sky)\
$azure\
$buf\
$dart\
$docker_context\
$elm\
$golang\
$perl\
$spack\
[](fg:sky bg:blue)\
$c\
$cobol\
$daml\
$gcloud\
$helm\
$kubernetes\
$lua\
$nix_shell\
$opa\
$rlang\
$singularity\
$vagrant\
$vlang\
[](fg:blue bg:lavender)\
$elixir\
$haskell\
$meson\
$php\
$solidity\
$terraform\
[](fg:lavender bg:subtext1)\
$custom\
$jobs\
$cmd_duration\
[ ](fg:subtext1)\
$line_break\
$character\
"""

# Inserts a blank line between shell prompts
add_newline = true

[aws]
symbol = " "
format = '[$symbol($profile )(\($region\) )(\[$duration\] )]($style)'
style = "bg:peach fg:mantle"

[azure]
symbol = " "
format = '[ $symbol($subscription) ]($style) '
style = "bg:sky fg:mantle"

[buf]
format = '[ $symbol($version) ]($style)'
style = "bg:sky fg:mantle"

[bun]
format = '[ $symbol($version) ]($style)'
style = "bg:rosewater fg:mantle"

[c]
format = '[ $symbol($version(-$name)) ]($style)'
symbol = " "
style = "bg:blue fg:mantle"

[character]
success_symbol = '[ 󱜙 ](fg:mantle bg:green)[ ](green)'
error_symbol = '[ 󱚝 ](fg:mantle bg:red)[ ](red)'
format = "$symbol"

[cmake]
format = '[ $symbol($version) ]($style)'
style = "bg:red fg:mantle"

[cobol]
format = '[ $symbol($version) ]($style)'
style = "bg:blue fg:mantle"

[cmd_duration]
format = '[ $duration ]($style)'
style = "bg:subtext1 fg:mantle bold"

[conda]
format = '[ $symbol$environment ]($style)'
style = "bg:green fg:mantle"

[container]
format = '[ $symbol \[$name\] ]($style)'
style = "bg:surface0 fg:text"

[crystal]
format = '[ $symbol($version) ]($style)'
symbol = " "
style = "bg:crust fg:text"

[daml]
format = '[ $symbol($version) ]($style)'
style = "bg:blue fg:mantle"

[dart]
format = '[ $symbol($version) ]($style)'
symbol = " "
style = "bg:sky fg:mantle"

[deno]
format = '[ $symbol($version) ]($style)'
style = "bg:crust fg:text"

[directory]
style = "bg:overlay1 fg:mantle"
format = "[ $path ]($style)"
truncation_length = 1
truncation_symbol = ""
read_only = " 󰌾"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
"~" = ""
# Keep in mind that the order matters. For example:
# "Important Documents" = " 󰈙 "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important 󰈙 " = " 󰈙 "

[docker_context]
format = '[ $symbol$context ]($style)'
symbol = " "
style = "bg:sky fg:mantle"

[dotnet]
symbol = "󰪮 "
format = '[ $symbol($version )(󰓾 $tfm) ]($style)'
style = "bg:mauve fg:mantle"

[elixir]
symbol = " "
format = '[ $symbol($version \(OTP $otp_version\)) ]($style)'
style = "bg:lavender fg:mantle"

[elm]
symbol = " "
format = '[ $symbol($version) ]($style)'
style = "bg:sky fg:mantle"

[env_var]
format = "[ $env_value ]($style)"
style = "bg:surface0 fg:text"

[erlang]
format = '[ $symbol($version) ]($style)'
symbol = " "
style = "bg:red fg:mantle"

[fennel]
format = '[ $symbol($version) ]($style)'
style = "bg:rosewater fg:mantle"

[gcloud]
format = '[ $symbol$account(@$domain)(\($region\)) ]($style)'
style = "bg:blue fg:mantle"

[git_branch]
symbol = " "
format = "[ $symbol $branch(:$remote_branch ) ]($style)"
style = "bg:surface0 fg:text bold"

[git_status]
style = "bg:surface0 fg:text"
format = '([\[$all_status$ahead_behind\] ]($style))'

[golang]
symbol = "󰟓 "
format = '[ $symbol($version) ]($style)'
style = "bg:sky fg:mantle"

[guix_shell]
symbol = " "
format = '[ $symbol ]($style)'
style = "bg:yellow fg:mantle"

[gradle]
symbol = " "
format = "[ $symbol($version) ]($style)"
style = "bg:teal fg:mantle"

[haskell]
symbol = " "
format = '[ $symbol($version) ]($style)'
style = "bg:lavender fg:mantle"

[haxe]
symbol = " "
format = "[ $symbol($version) ]($style)"
style = "bg:peach fg:mantle"

[helm]
symbol = "󰠳 "
format = '[ $symbol($version) ]($style)'
style = "bg:blue fg:mantle"

[hostname]
format = '[ $symbol($version) ]($style)'
style = "bg:overlay1 fg:mantle"

[java]
symbol = " "
format = '[ ${symbol}(${version}) ]($style)'
style = "bg:red fg:mantle"

[jobs]
format = '[ $symbol$number ]($style)'
symbol = " "
style = "bg:subtext1 fg:mantle"

[julia]
symbol = " "
style = "bg:green fg:mantle"
format = '[ $symbol($version) ]($style)'

[kotlin]
symbol = " "
format = '[ $symbol($version) ]($style)'
style = "bg:mauve fg:mantle"

[kubernetes]
symbol = "󱃾 "
format = '[ $symbol$context( \($namespace\)) ]($style)'
style = "bg:blue fg:mantle"

[lua]
symbol = " "
style = "bg:blue fg:mantle"
format = '[ $symbol($version) ]($style)'

[memory_usage]
symbol = "󰍛 "
style = "bg:green fg:mantle"
format = '$symbol [ ${ram}( \| ${swap}) ]($style)'

[meson]
symbol = "󰔷 "
style = "bg:lavender fg:mantle"
format = '[ $symbol$project ]($style)'

[hg_branch]
format = '[ $symbol$branch(:$topic) ]($style)'
symbol = " "
style = "bg:surface0 fg:text bold"

[nim]
symbol = " "
format = "[ $symbol($version) ]($style)"
style = "bg:yellow fg:mantle"

[nix_shell]
symbol = " "
style = "bg:blue fg:mantle"
format = '[ $symbol$state( \($name\)) ]($style)'

[nodejs]
symbol = " "
style = "bg:green fg:mantle"
format = '[ $symbol($version) ]($style)'

[ocaml]
symbol = " "
style = "bg:peach fg:mantle"
format = '[ $symbol($version )(\($switch_indicator$switch_name\)) ]($style)'

[opa]
format = '[ $symbol($version) ]($style)'
style = "bg:blue fg:mantle"

[openstack]
format = '[ $symbol$cloud(\($project\)) ]($style)'
style = "bg:red fg:mantle"

# An alternative to the username module which displays a symbol that
# represents the current operating system
[os]
style = "bg:sapphire fg:mantle"
disabled = false # Disabled by default

[os.symbols]
Alpaquita = " "
Alpine = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Windows = "󰍲 "

[package]
symbol = "󰏗 "
format = '[ $symbol$version ]($style)'
style = "bg:maroon fg:mantle"

[perl]
format = '[ $symbol($version) ]($style)'
symbol = " "
style = "bg:sky fg:mantle"

[php]
style = "bg:blue fg:mantle"
format = '[ $symbol($version) ]($style)'
symbol = " "

[pijul_channel]
symbol = " "
format = '[ $symbol$channel ]($style)'
style = "bg:surface0 fg:text bold"

[purescript]
format = '[ $symbol($version) ]($style)'
symbol = " "
style = "bg:teal fg:mantle"

[python]
symbol = " "
style = "bg:yellow fg:mantle"
format = '[ ${symbol}${pyenv_prefix}(${version} )(\($virtualenv\)) ]($style)'

[rlang]
symbol = "󰟔 "
format = '[ $symbol($version) ]($style)'
style = "bg:blue fg:mantle"

[raku]
format = '[ $symbol($version-$vm_version) ]($style)'
style = "bg:pink fg:mantle"

[red]
format = '[ $symbol($version) ]($style)'
style = "bg:red fg:mantle"

[ruby]
symbol = " "
style = "bg:red fg:mantle"
format = '[ $symbol($version) ]($style)'

[rust]
symbol = " "
style = "bg:peach fg:mantle"
format = '[ $symbol($version) ]($style)'

[scala]
symbol = " "
format = '[ ${symbol}(${version}) ]($style)'
style = "bg:red fg:mantle"

[singularity]
format = '[ $symbol\[$env\] ]($style)'
style = "bg:blue fg:mantle"

[solidity]
style = "bg:lavender fg:mantle"
format = "[ $symbol($version) ]($style)"

[spack]
style = "bg:sky fg:mantle"
format = '[ $symbol$environment ]($style)'

[swift]
style = "bg:peach fg:mantle"
format = '[ $symbol($version) ]($style)'
symbol = " "

[terraform]
style = "bg:lavender fg:mantle"
format = '[ $symbol$workspace ]($style)'
symbol = "󱁢 "

[username]
disabled = true

[vagrant]
style = "bg:blue fg:mantle"
format = '[ $symbol($version) ]($style)'

[vlang]
format = '[ $symbol($version) ]($style)'
style = "bg:blue fg:mantle"
symbol = " "

[vcsh]
format = ' vcsh[ $repo ]($style)'
style = "bg:surface0 fg:text bold"

[zig]
format = '[ $symbol($version) ]($style)'
symbol = " "
style = "bg:yellow fg:mantle" 

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
